CALC_DTYPES = {
    'success': 'bool[pyarrow]',
    'baseline': 'float64[pyarrow]',
    'cde': 'bool[pyarrow]',
    'duration': 'int64[pyarrow]',
    'post_induction_mean': 'float64[pyarrow]',
    'mean': 'float64[pyarrow]',
    'drop': 'float64[pyarrow]',
    'min': 'float64[pyarrow]',
    'max': 'float64[pyarrow]',
    'std': 'float64[pyarrow]',
    'mean15': 'float64[pyarrow]',
    'min5': 'float64[pyarrow]',
    'min10': 'float64[pyarrow]',
    'min15': 'float64[pyarrow]',
    'min20': 'float64[pyarrow]',
    'min25': 'float64[pyarrow]',
    'min30': 'float64[pyarrow]',
    'min_post': 'float64[pyarrow]',
    'aac40': 'float64[pyarrow]',
    'aac45': 'float64[pyarrow]',
    'aac50': 'float64[pyarrow]',
    'aac55': 'float64[pyarrow]',
    'aac60': 'float64[pyarrow]',
    'aac65': 'float64[pyarrow]',
    'aac70': 'float64[pyarrow]',
}

FHDB_BOOL_T_F = {
    'event_marker',
    'nirs_data_usable',
    'pilot',
    'not_atscene',
    'gu_prognosis',
    'escorted.1',
    'ba_none',
    'ba_jaw',
    'ba_opanpa',
    'ba_manual',
    'ba_mechanical',
    'ba_pleural',
    'ba_thoracostomy',
    'cp_none',
    'cp_iv',
    'cp_central',
    'cp_io',
    'cp_defib',
    'cp_cardioversion',
    'cp_extpacing',
    'cp_hemostatic_b',
    'cp_hemostatic_a',
    'cp_other',
    'dp_none',
    'dp_fract',
    'dp_spinal',
    'dp_hypo',
    'dp_other',
    'mm_none',
    'mm_analgesic.1',
    'mm_sedative.1',
    'mm_nmba',
    'mm_vasoactive',
    'mm_fibrinolytic',
    'mm_antibiotic',
    'mm_other',
    'dgp_none',
    'dgp_ultra',
    'dgp_ecg',
    'dgp_invmonit',
    'dgp_poclab',
    'dgp_other',
    'r_attempted',
    'r_cardiac',
    'r_bcpr',
    'aw_compl_esophageal',
    'aw_compl_bronchus',
    'aw_compl_teeth',
    'aw_compl_aspiration',
    'aw_compl_hypoxia',
    'aw_compl_brady',
    'aw_compl_hypotension',
    'o2_i.1',
    'lgstc_30min_plus',
    'lgstc_15_to_29min',
    'lgstc_evacuate',
    'lgstc_none',
    'ad_esketamine.1',
    'ad_propofol.1',
    'ad_fentanyl.1',
    'ad_rocuronium.1',
    'ad_vasopressor.1',
    'ad_midazolam.1',
    'ad_succinylcholine.1',
    'ad_lidocaine.1',
    'ad_etomidate.1',
    'ad_other',
    'ba_niv',
    'cp_hemostatic_a_duplicate',
    'cpha_tourniquet',
    'cpha_pressure_dressing',
    'cpha_hemostatic',
    'cpha_itclamp',
    'cpha_other',
    'cp_transfusion',
    'cp_transf_rbc',
    'cp_transf_plasma',
    'cp_transf_other',
    'cp_arterial',
    'dp_thoracotomy',
    'dp_c_section',
    'dp_reboa',
    'dp_aajt',
    'dp_pelvic',
    'dp_child_delivery',
    'mm_other_duplicate',
    'mm_tranexamic',
    'mm_anticonvulsive',
    'mm_antiemetic',
    'mm_antidote',
    'mm_antiarrythmic',
    'dgp_examination',
    'hypothermia',
    'r_mechanical',
    'awpr_none',
    'awpr_prior_diff',
    'awpr_reduc_mob',
    'awpr_obese',
    'awpr_mouth',
    'awpr_tmd',
    'awpr_trauma',
    'awpr_exist_dev',
    'awpr_mucus_etc',
    'awpr_other',
    'awpr_not_assessed',
    'awec_none',
    'awec_entrapped',
    'awec_no360',
    'awec_subopt_pos',
    'awec_bright',
    'awec_dark',
    'awec_hostile',
    'awec_moving_veh',
    'awec_stationary_veh',
    'awec_other',
    'awos_none',
    'awos_nonbreath_mask',
    'awos_bag_valve',
    'awos_apneic',
    'awos_niv',
    'awos_supraglottic',
    'awm_cricoid',
    'awm_burp_elm',
    'awm_mils',
    'awm_reposition',
    'awm_ramping',
    'awm_none',
    'aw_compl_oth',
    'aw_compl_surg_percut',
    'aw_compl_final_aw_failed'
}

FHDB_DTYPES = {
    'CID': 'int64[pyarrow]',
    'kirjattu': 'string[pyarrow]',
    'kirjaaja': 'string[pyarrow]',
    'pvm_klo': 'string[pyarrow]',
    'code': 'string[pyarrow]',
    'doc': 'string[pyarrow]',
    'patient_name': 'string[pyarrow]',
    'address': 'string[pyarrow]',
    'r_id': 'int64[pyarrow]',
    'case_id': 'int64[pyarrow]',
    'inclusion': 'bool[pyarrow]',
    'excl_reason': 'int64[pyarrow]',
    'excl_reason_other': 'string[pyarrow]',
    'own_defib': 'bool[pyarrow]',
    'poc_sample': 'bool[pyarrow]',
    'ane_stamp': 'string[pyarrow]',
    'no_ane_stamp': 'bool[pyarrow]',
    'adverse': 'bool[pyarrow]',
    'adverse_detail': 'string[pyarrow]',
    'equip_failure': 'bool[pyarrow]',
    'eqf_detail': 'string[pyarrow]',
    'no_access': 'bool[pyarrow]',
    'dod': 'string[pyarrow]',
    'discharge_time': 'string[pyarrow]',
    'dg1': 'string[pyarrow]',
    'dg1_code': 'string[pyarrow]',
    'dg1_long_name': 'string[pyarrow]',
    'dg2': 'string[pyarrow]',
    'dg2_code': 'string[pyarrow]',
    'dg2_long_name': 'string[pyarrow]',
    'dg3': 'string[pyarrow]',
    'dg3_code': 'string[pyarrow]',
    'dg3_long_name': 'string[pyarrow]',
    'injury_mech': 'int64[pyarrow]',
    'im_code': 'string[pyarrow]',
    'im_long_name': 'string[pyarrow]',
    'ventilator_days': 'int64[pyarrow]',
    'consent': 'int64[pyarrow]',
    'death': 'bool[pyarrow]',
    'nirs_data': 'bool[pyarrow]',
    'nirs_usb': 'bool[pyarrow]',
    'nirs_network': 'bool[pyarrow]',
    'no_nirs': 'bool[pyarrow]',
    'no_nirs_detail': 'string[pyarrow]',
    'defib_data': 'bool[pyarrow]',
    'defib_usb': 'bool[pyarrow]',
    'defib_network': 'bool[pyarrow]',
    'no_defib': 'bool[pyarrow]',
    'no_defib_detail': 'string[pyarrow]',
    'status': 'bool[pyarrow]',
    'approved': 'bool[pyarrow]',
    'event_marker': 'string[pyarrow]',
    'ra_comments': 'string[pyarrow]',
    'nirs_data_usable': 'string[pyarrow]',
    'nirs_data_unusable_detail': 'string[pyarrow]',
    'mrs30': 'int64[pyarrow]',
    'mrs_source': 'int64[pyarrow]',
    'mrs365': 'int64[pyarrow]',
    'mrs365_source': 'int64[pyarrow]',
    'pilot': 'string[pyarrow]',
    'anaesthetic': 'int64[pyarrow]',
    'anae_bits': 'string[pyarrow]',
    'anae_none': 'bool[pyarrow]',
    'anae_esketamine': 'bool[pyarrow]',
    'anae_propofol': 'bool[pyarrow]',
    'anae_midazolam': 'bool[pyarrow]',
    'maintenance': 'string[pyarrow]',
    'maint_bits': 'string[pyarrow]',
    'maint_none': 'bool[pyarrow]',
    'maint_esketamine': 'bool[pyarrow]',
    'maint_propofol': 'bool[pyarrow]',
    'maint_midazolam': 'bool[pyarrow]',
    'maint_fentanyl': 'bool[pyarrow]',
    'maint_morphine': 'bool[pyarrow]',
    'maint_oxidocone': 'bool[pyarrow]',
    'maint_rocuronium': 'bool[pyarrow]',
    'maint_other': 'bool[pyarrow]',
    'maintenance_other': 'string[pyarrow]',
    'lq15d_1': 'int64[pyarrow]',
    'lq15d_2': 'int64[pyarrow]',
    'lq15d_3': 'int64[pyarrow]',
    'lq15d_4': 'int64[pyarrow]',
    'lq15d_5': 'int64[pyarrow]',
    'lq15d_6': 'int64[pyarrow]',
    'lq15d_7': 'int64[pyarrow]',
    'lq15d_8': 'int64[pyarrow]',
    'lq15d_9': 'int64[pyarrow]',
    'lq15d_10': 'int64[pyarrow]',
    'lq15d_11': 'int64[pyarrow]',
    'lq15d_12': 'int64[pyarrow]',
    'lq15d_13': 'int64[pyarrow]',
    'lq15d_14': 'int64[pyarrow]',
    'lq15d_15': 'int64[pyarrow]',
    'base': 'string[pyarrow]',
    't_atscene': 'string[pyarrow]',
    't_atpatient': 'string[pyarrow]',
    't_transport': 'string[pyarrow]',
    't_athospital': 'string[pyarrow]',
    'asa': 'int64[pyarrow]',
    'ecog': 'int64[pyarrow]',
    'mmr': 'int64[pyarrow]',
    'ad_esketamine': 'bool[pyarrow]',
    'ad_propofol': 'bool[pyarrow]',
    'ad_fentanyl': 'bool[pyarrow]',
    'ad_rocuronium': 'bool[pyarrow]',
    'ad_vasopressor': 'bool[pyarrow]',
    'ad_midazolam': 'bool[pyarrow]',
    'ad_succinylcholine': 'bool[pyarrow]',
    'ad_lidocaine': 'bool[pyarrow]',
    'ad_etomidate': 'bool[pyarrow]',
    'airway': 'int64[pyarrow]',
    'mm_analgesic': 'bool[pyarrow]',
    'mm_sedative': 'bool[pyarrow]',
    'pulse1': 'string[pyarrow]',
    'rr1': 'string[pyarrow]',
    'resp1': 'int64[pyarrow]',
    'spo21': 'int64[pyarrow]',
    'etco21': 'float64[pyarrow]',
    'r_arrest': 'bool[pyarrow]',
    'attempted': 'bool[pyarrow]',
    'pulse_p': 'string[pyarrow]',
    'pulse_f': 'int64[pyarrow]',
    'bp_p': 'string[pyarrow]',
    'bp_f': 'string[pyarrow]',
    'resp_p': 'int64[pyarrow]',
    'resp_f': 'int64[pyarrow]',
    'spo2_p': 'int64[pyarrow]',
    'spo2_f': 'int64[pyarrow]',
    'o2_i': 'bool[pyarrow]',
    'etco2_p': 'float64[pyarrow]',
    'etco2_f': 'float64[pyarrow]',
    'owncode': 'string[pyarrow]',
    'escorted': 'bool[pyarrow]',
    'sex': 'int64[pyarrow]',
    'accurate_ssid': 'string[pyarrow]',
    'approx_birthyear': 'string[pyarrow]',
    'approx_age': 'int64[pyarrow]',
    'gcse1': 'int64[pyarrow]',
    'gcsv1': 'int64[pyarrow]',
    'gcsm1': 'int64[pyarrow]',
    'gcst1': 'int64[pyarrow]',
    'survival': 'int64[pyarrow]',
    'alarm_to_patient': 'int64[pyarrow]',
    'atscene_duration': 'int64[pyarrow]',
    'transport_duration': 'int64[pyarrow]',
    'poc1_stamp': 'string[pyarrow]',
    'poc1_id': 'int64[pyarrow]',
    'poc1_rank': 'int64[pyarrow]',
    'poc1_r5': 'int64[pyarrow]',
    'poc1_na': 'int64[pyarrow]',
    'poc1_k': 'float64[pyarrow]',
    'poc1_ca': 'float64[pyarrow]',
    'poc1_gluc': 'float64[pyarrow]',
    'poc1_hkr': 'int64[pyarrow]',
    'poc1_hb': 'int64[pyarrow]',
    'poc1_lact': 'float64[pyarrow]',
    'poc1_ph': 'float64[pyarrow]',
    'poc1_pco2': 'float64[pyarrow]',
    'poc1_po2': 'float64[pyarrow]',
    'poc1_tco2': 'int64[pyarrow]',
    'poc1_hco3': 'float64[pyarrow]',
    'poc1_be': 'int64[pyarrow]',
    'poc1_so2': 'int64[pyarrow]',
    'poc2_stamp': 'string[pyarrow]',
    'poc2_id': 'int64[pyarrow]',
    'poc2_rank': 'int64[pyarrow]',
    'poc2_r5': 'int64[pyarrow]',
    'poc2_na': 'int64[pyarrow]',
    'poc2_k': 'float64[pyarrow]',
    'poc2_ca': 'float64[pyarrow]',
    'poc2_gluc': 'float64[pyarrow]',
    'poc2_hkr': 'int64[pyarrow]',
    'poc2_hb': 'int64[pyarrow]',
    'poc2_lact': 'float64[pyarrow]',
    'poc2_ph': 'float64[pyarrow]',
    'poc2_pco2': 'float64[pyarrow]',
    'poc2_po2': 'float64[pyarrow]',
    'poc2_tco2': 'int64[pyarrow]',
    'poc2_hco3': 'float64[pyarrow]',
    'poc2_be': 'int64[pyarrow]',
    'poc2_so2': 'int64[pyarrow]',
    'poc3_stamp': 'string[pyarrow]',
    'poc3_id': 'int64[pyarrow]',
    'poc3_rank': 'int64[pyarrow]',
    'poc3_r5': 'int64[pyarrow]',
    'poc3_na': 'int64[pyarrow]',
    'poc3_k': 'float64[pyarrow]',
    'poc3_ca': 'float64[pyarrow]',
    'poc3_gluc': 'float64[pyarrow]',
    'poc3_hkr': 'int64[pyarrow]',
    'poc3_hb': 'int64[pyarrow]',
    'poc3_lact': 'float64[pyarrow]',
    'poc3_ph': 'float64[pyarrow]',
    'poc3_pco2': 'float64[pyarrow]',
    'poc3_po2': 'float64[pyarrow]',
    'poc3_tco2': 'int64[pyarrow]',
    'poc3_hco3': 'float64[pyarrow]',
    'poc3_be': 'int64[pyarrow]',
    'poc3_so2': 'int64[pyarrow]',
    'accurate_ssid.1': 'float64[pyarrow]',
    'approx_birthyear.1': 'float64[pyarrow]',
    'approx_age.1': 'int64[pyarrow]',
    'combined_age': 'float64[pyarrow]',
    'dispatcher': 'string[pyarrow]',
    'facility_type': 'string[pyarrow]',
    't_call': 'string[pyarrow]',
    't_ontheway': 'string[pyarrow]',
    't_available': 'string[pyarrow]',
    't_end': 'string[pyarrow]',
    'evy_type': 'int64[pyarrow]',
    'saku_alarm': 'string[pyarrow]',
    'saku_atscene': 'string[pyarrow]',
    'dep_delay': 'string[pyarrow]',
    'dep_delay_other': 'string[pyarrow]',
    'not_atscene': 'string[pyarrow]',
    'register': 'string[pyarrow]',
    'gu_reason': 'string[pyarrow]',
    'gu_prognosis': 'string[pyarrow]',
    'owncode.1': 'string[pyarrow]',
    'at_alarm': 'bool[pyarrow]',
    'score': 'int64[pyarrow]',
    'dg1.1': 'string[pyarrow]',
    'dg2.1': 'string[pyarrow]',
    'icpc2_1': 'string[pyarrow]',
    'icpc2_2': 'string[pyarrow]',
    'tr_code': 'string[pyarrow]',
    'escorted.1': 'string[pyarrow]',
    'hospital': 'string[pyarrow]',
    'survival.1': 'string[pyarrow]',
    'logistics': 'string[pyarrow]',
    'asa.1': 'int64[pyarrow]',
    'ecog.1': 'int64[pyarrow]',
    'mmr.1': 'int64[pyarrow]',
    'i_type': 'int64[pyarrow]',
    'a_drugs': 'int64[pyarrow]',
    'ad_none': 'string[pyarrow]',
    'ad_sedative': 'string[pyarrow]',
    'ad_nmba': 'string[pyarrow]',
    'ad_analgesic': 'string[pyarrow]',
    'ad_localanesth': 'string[pyarrow]',
    'airway.1': 'int64[pyarrow]',
    'b_assist': 'string[pyarrow]',
    'ba_none': 'string[pyarrow]',
    'ba_jaw': 'string[pyarrow]',
    'ba_opanpa': 'string[pyarrow]',
    'ba_manual': 'string[pyarrow]',
    'ba_mechanical': 'string[pyarrow]',
    'ba_pleural': 'string[pyarrow]',
    'ba_thoracostomy': 'string[pyarrow]',
    'c_proc': 'string[pyarrow]',
    'cp_none': 'string[pyarrow]',
    'cp_iv': 'string[pyarrow]',
    'cp_central': 'string[pyarrow]',
    'cp_io': 'string[pyarrow]',
    'cp_defib': 'string[pyarrow]',
    'cp_cardioversion': 'string[pyarrow]',
    'cp_extpacing': 'string[pyarrow]',
    'cp_hemostatic_b': 'string[pyarrow]',
    'cp_hemostatic_a': 'string[pyarrow]',
    'cp_other': 'string[pyarrow]',
    'c_proc_other': 'string[pyarrow]',
    'd_proc': 'string[pyarrow]',
    'dp_none': 'string[pyarrow]',
    'dp_fract': 'string[pyarrow]',
    'dp_spinal': 'string[pyarrow]',
    'dp_hypo': 'string[pyarrow]',
    'dp_other': 'string[pyarrow]',
    'd_proc_other': 'string[pyarrow]',
    'm_med': 'string[pyarrow]',
    'mm_none': 'string[pyarrow]',
    'mm_analgesic.1': 'string[pyarrow]',
    'mm_sedative.1': 'string[pyarrow]',
    'mm_nmba': 'string[pyarrow]',
    'mm_vasoactive': 'string[pyarrow]',
    'mm_fibrinolytic': 'string[pyarrow]',
    'mm_antibiotic': 'string[pyarrow]',
    'mm_other': 'string[pyarrow]',
    'dg_proc': 'string[pyarrow]',
    'dgp_none': 'string[pyarrow]',
    'dgp_ultra': 'string[pyarrow]',
    'dgp_ecg': 'string[pyarrow]',
    'dgp_invmonit': 'string[pyarrow]',
    'dgp_poclab': 'string[pyarrow]',
    'dgp_other': 'string[pyarrow]',
    'dg_proc_other': 'string[pyarrow]',
    'gcse1.1': 'int64[pyarrow]',
    'gcsv1.1': 'int64[pyarrow]',
    'gcsm1.1': 'int64[pyarrow]',
    'gcst1.1': 'int64[pyarrow]',
    'rhythm1': 'int64[pyarrow]',
    'pulse1.1': 'string[pyarrow]',
    'rr1.1': 'string[pyarrow]',
    'resp1.1': 'int64[pyarrow]',
    'spo21.1': 'int64[pyarrow]',
    'etco21.1': 'string[pyarrow]',
    'pain1': 'int64[pyarrow]',
    'gcse2': 'int64[pyarrow]',
    'gcsv2': 'int64[pyarrow]',
    'gcsm2': 'int64[pyarrow]',
    'gcst2': 'int64[pyarrow]',
    'rhythm2': 'int64[pyarrow]',
    'pulse2': 'string[pyarrow]',
    'rr2': 'string[pyarrow]',
    'resp2': 'int64[pyarrow]',
    'spo22': 'int64[pyarrow]',
    'etco22': 'string[pyarrow]',
    'pain2': 'int64[pyarrow]',
    'r_attempted': 'string[pyarrow]',
    'r_cardiac': 'string[pyarrow]',
    'r_witnessed': 'int64[pyarrow]',
    'r_irhythm': 'int64[pyarrow]',
    'r_bcpr': 'string[pyarrow]',
    'r_rosc': 'int64[pyarrow]',
    'r_t_arrest': 'string[pyarrow]',
    'r_t_trosc': 'string[pyarrow]',
    'r_t_prosc': 'string[pyarrow]',
    'aw_indication': 'string[pyarrow]',
    'aw_ind_other': 'string[pyarrow]',
    'aw_secured_by': 'string[pyarrow]',
    'aw_intervention_attempts': 'int64[pyarrow]',
    'aw_intub_success': 'string[pyarrow]',
    'aw_compl_esophageal': 'string[pyarrow]',
    'aw_compl_bronchus': 'string[pyarrow]',
    'aw_compl_teeth': 'string[pyarrow]',
    'aw_compl_aspiration': 'string[pyarrow]',
    'aw_compl_hypoxia': 'string[pyarrow]',
    'aw_compl_brady': 'string[pyarrow]',
    'aw_compl_hypotension': 'string[pyarrow]',
    'aw_compl_other': 'string[pyarrow]',
    'failed_i': 'string[pyarrow]',
    'gcse_i': 'int64[pyarrow]',
    'gcsv_i': 'int64[pyarrow]',
    'gcsm_i': 'int64[pyarrow]',
    'pulse_i': 'string[pyarrow]',
    'pulse_p.1': 'string[pyarrow]',
    'pulse_f.1': 'int64[pyarrow]',
    'bp_i': 'string[pyarrow]',
    'bp_p.1': 'string[pyarrow]',
    'bp_f.1': 'string[pyarrow]',
    'resp_i': 'int64[pyarrow]',
    'resp_p.1': 'int64[pyarrow]',
    'resp_f.1': 'int64[pyarrow]',
    'spo2_i': 'int64[pyarrow]',
    'spo2_p.1': 'int64[pyarrow]',
    'spo2_f.1': 'int64[pyarrow]',
    'o2_i.1': 'string[pyarrow]',
    'etco2_p.1': 'string[pyarrow]',
    'etco2_f.1': 'string[pyarrow]',
    'alarm_to_patient.1': 'int64[pyarrow]',
    'atscene_duration.1': 'int64[pyarrow]',
    'transport_duration.1': 'int64[pyarrow]',
    'sex.1': 'int64[pyarrow]',
    'accurate_ssid.2': 'float64[pyarrow]',
    'approx_birthyear.2': 'float64[pyarrow]',
    'approx_age.2': 'int64[pyarrow]',
    'awa_secured_by_final': 'string[pyarrow]',
    'awa_intervention_attempts': 'string[pyarrow]',
    'awa_intub_success': 'string[pyarrow]',
    'naca': 'int64[pyarrow]',
    'logistics_5bits': 'string[pyarrow]',
    'lgstc_30min_plus': 'string[pyarrow]',
    'lgstc_15_to_29min': 'string[pyarrow]',
    'lgstc_evacuate': 'string[pyarrow]',
    'lgstc_none': 'string[pyarrow]',
    'initial_airway': 'string[pyarrow]',
    'a_drugs_20bits': 'string[pyarrow]',
    'ad_esketamine.1': 'string[pyarrow]',
    'ad_propofol.1': 'string[pyarrow]',
    'ad_fentanyl.1': 'string[pyarrow]',
    'ad_rocuronium.1': 'string[pyarrow]',
    'ad_vasopressor.1': 'string[pyarrow]',
    'ad_midazolam.1': 'string[pyarrow]',
    'ad_succinylcholine.1': 'string[pyarrow]',
    'ad_lidocaine.1': 'string[pyarrow]',
    'ad_etomidate.1': 'string[pyarrow]',
    'ad_other': 'string[pyarrow]',
    'a_drugs_other': 'string[pyarrow]',
    'b_assist_8bits': 'string[pyarrow]',
    'ba_niv': 'string[pyarrow]',
    'c_proc_11bits': 'string[pyarrow]',
    'cp_hemostatic_a_duplicate': 'string[pyarrow]',
    'cpha_tourniquet': 'string[pyarrow]',
    'cpha_pressure_dressing': 'string[pyarrow]',
    'cpha_hemostatic': 'string[pyarrow]',
    'cpha_itclamp': 'string[pyarrow]',
    'cpha_other': 'string[pyarrow]',
    'c_cpha_other': 'string[pyarrow]',
    'cp_transfusion': 'string[pyarrow]',
    'cp_transf_rbc': 'string[pyarrow]',
    'cp_transf_plasma': 'string[pyarrow]',
    'cp_transf_other': 'string[pyarrow]',
    'c_transfusion_other': 'string[pyarrow]',
    'cp_arterial': 'string[pyarrow]',
    'd_proc_11bits': 'string[pyarrow]',
    'dp_thoracotomy': 'string[pyarrow]',
    'dp_c_section': 'string[pyarrow]',
    'dp_reboa': 'string[pyarrow]',
    'dp_aajt': 'string[pyarrow]',
    'dp_pelvic': 'string[pyarrow]',
    'dp_child_delivery': 'string[pyarrow]',
    'm_med_13bits': 'string[pyarrow]',
    'mm_other_duplicate': 'string[pyarrow]',
    'm_med_other': 'string[pyarrow]',
    'mm_tranexamic': 'string[pyarrow]',
    'mm_anticonvulsive': 'string[pyarrow]',
    'mm_antiemetic': 'string[pyarrow]',
    'mm_antidote': 'string[pyarrow]',
    'mm_antiarrythmic': 'string[pyarrow]',
    'dg_proc_8bits': 'string[pyarrow]',
    'dgp_examination': 'string[pyarrow]',
    'hypothermia': 'string[pyarrow]',
    'temp1': 'string[pyarrow]',
    'temp2': 'string[pyarrow]',
    'r_reason': 'string[pyarrow]',
    'r_mechanical': 'string[pyarrow]',
    'aw_p_risk': 'string[pyarrow]',
    'awpr_none': 'string[pyarrow]',
    'awpr_prior_diff': 'string[pyarrow]',
    'awpr_reduc_mob': 'string[pyarrow]',
    'awpr_obese': 'string[pyarrow]',
    'awpr_mouth': 'string[pyarrow]',
    'awpr_tmd': 'string[pyarrow]',
    'awpr_trauma': 'string[pyarrow]',
    'awpr_exist_dev': 'string[pyarrow]',
    'awpr_mucus_etc': 'string[pyarrow]',
    'awpr_other': 'string[pyarrow]',
    'p_risk_other': 'string[pyarrow]',
    'awpr_not_assessed': 'string[pyarrow]',
    'aw_e_cond': 'string[pyarrow]',
    'awec_none': 'string[pyarrow]',
    'awec_entrapped': 'string[pyarrow]',
    'awec_no360': 'string[pyarrow]',
    'awec_subopt_pos': 'string[pyarrow]',
    'awec_bright': 'string[pyarrow]',
    'awec_dark': 'string[pyarrow]',
    'awec_hostile': 'string[pyarrow]',
    'awec_moving_veh': 'string[pyarrow]',
    'awec_stationary_veh': 'string[pyarrow]',
    'awec_other': 'string[pyarrow]',
    'e_cond_other': 'string[pyarrow]',
    'checklist': 'string[pyarrow]',
    'aw_o_strategy': 'string[pyarrow]',
    'awos_none': 'string[pyarrow]',
    'awos_nonbreath_mask': 'string[pyarrow]',
    'awos_bag_valve': 'string[pyarrow]',
    'awos_apneic': 'string[pyarrow]',
    'awos_niv': 'string[pyarrow]',
    'awos_supraglottic': 'string[pyarrow]',
    'ventilation': 'string[pyarrow]',
    'aw_manoeuvre': 'string[pyarrow]',
    'awm_cricoid': 'string[pyarrow]',
    'awm_burp_elm': 'string[pyarrow]',
    'awm_mils': 'string[pyarrow]',
    'awm_reposition': 'string[pyarrow]',
    'awm_ramping': 'string[pyarrow]',
    'awm_none': 'string[pyarrow]',
    'aw_complications': 'string[pyarrow]',
    'aw_compl_oth': 'string[pyarrow]',
    'aw_compl_esophageal_det': 'string[pyarrow]',
    'aw_compl_positioning': 'string[pyarrow]',
    'aw_compl_cardiac_arr': 'string[pyarrow]',
    'aw_compl_surg_percut': 'string[pyarrow]',
    'aw_compl_final_aw_failed': 'string[pyarrow]',
    'bp_pre': 'string[pyarrow]',
    'spo2_pre': 'int64[pyarrow]',
    'bp_proc': 'string[pyarrow]',
    'spo2_proc': 'int64[pyarrow]',
    'gcse_pre': 'int64[pyarrow]',
    'gcsv_pre': 'int64[pyarrow]',
    'gcsm_pre': 'int64[pyarrow]',
    'etco21_comma': 'float64[pyarrow]',
    'etco22_comma': 'float64[pyarrow]',
    'etco2_p_comma': 'float64[pyarrow]',
    'etco2_f_comma': 'float64[pyarrow]',
    'aw2_number_of_attempts': 'int64[pyarrow]',
    'aw2_device_1st': 'string[pyarrow]',
    'aw2_extra_1st': 'string[pyarrow]',
    'aw2_attempter_1st': 'string[pyarrow]',
    'aw2_device_2nd': 'string[pyarrow]',
    'aw2_extra_2nd': 'string[pyarrow]',
    'aw2_attempter_2nd': 'string[pyarrow]',
    'aw2_device_3rd': 'string[pyarrow]',
    'aw2_extra_3rd': 'string[pyarrow]',
    'aw2_attempter_3rd': 'string[pyarrow]',
    'aw2_device_4th': 'string[pyarrow]',
    'aw2_extra_4th': 'string[pyarrow]',
    'aw2_attempter_4th': 'string[pyarrow]',
    'aw2_device_5th': 'string[pyarrow]',
    'aw2_extra_5th': 'string[pyarrow]',
    'aw2_attempter_5th': 'string[pyarrow]',
}
